language: ruby
before_install:
  - echo -e "machine github.com\n  login $GITHUB_ACCESS_TOKEN" >> ~/.netrc
script:
  - bundle exec rake close_old_pull_requests pull_request_summary:travis || true
  - bundle exec rake
after_success:
  - scripts/deploy.sh
cache: bundler
rvm:
  - 2.4.4
env:
  global:
    secure: ZCQVQdKDUyPY/BM1FYriv6h+rNF+PqQETnj5FwU/jQKNz8utvaUVjXD/pIMwEmO5orzng5/MnZvErkr2+JZBs+0JghXWtjDxQHxJzfBTZJnaiAY9hWZBC9Kgbl1/mJvUvK132W5GzQ5xS9lw/pyKFGRba9A7rfoYFfkaJKmgq1U=
notifications:
  slack:
    rooms:
      - secure: KGGTh4XFNqQ4TrQB90B++X4q4jOohQxsZatRk54cYqZOSsrLm8CEJU4eBFVfhQ0p/iiYIBwfZlECyjMgKR+3OUYAAcHGuPSuE5q9M9KUi+c5O11Lx02lQAwhMzUXR0/BmKiUYWssOdV7RsfG3VXOu7vUKmapcT+oQUHmbRd+b8U=
    on_success: never
